SET IDENTITY_INSERT [dbo].[Kinds] ON
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (1, N'Food and Drink', N'about food11', N'https://million-wallpapers.ru/wallpapers/1/71/15642823563272717331.jpg')
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (2, N'Sport equipment', N'about ', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (3, N'Technology and IT', N'adasdas', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (4, N'asdasd', N'asdasd', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (5, N'asdasd', N'asdasd', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (6, N'sasd', N'asdasdas', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (7, N'asdasdasd', N'asdasdasd', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (8, N'asdasdasd', N'dasdasdasd', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (9, N'asdasdasd', N'dasdasdas', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (10, N'asdasdasdasd', N'asdasdasdasd', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (11, N'asdasdasd', N'asdasdasd', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (12, N'rqwer', N'qewrqwer', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (13, N'ewqrwqer', N'qwerqwer', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (14, N'qwerqwe', N'qwerqwer', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (15, N'qewrewr', N'werwerwer', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (16, N'qewrqwer', N'qwerqwer', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (17, N'tttttttttttt', N'ttttt', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (18, N'qweqwe', N'qweqwe', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (19, N'rrrrrrrrrr', N'rrrrrrrrrrrrrr', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (20, N'qqqqqqqqqqq', N'qqqqqqqqqqqq', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (21, N'uuuuuuuuu', N'uuuuuuuuuuuuuu', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (22, N'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk', N'k', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (23, N'weqw', N'qwe', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (24, N'qweqw', N'qweqwe', NULL)
INSERT INTO [dbo].[Kinds] ([KindId], [Name], [About], [Foto]) VALUES (25, N'sdfsd', N'sdfsdf', NULL)
SET IDENTITY_INSERT [dbo].[Kinds] OFF
